apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "kubernetes-cluster-mohitgoyal"
  labels:
    name: "kubernetes-cluster-mohitgoyal"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: kubernetes-cluster-mohitgoyal
  labels:
    app: special-config
data:
  API_URL: "https://api.spaceXdata.com/v3/launches?limit=100"
  ENVIRONMENT: "dev"
  dev_production_flag: "False"
---
apiVersion: v1
kind: Secret
metadata:
  name: top-secret
  namespace: kubernetes-cluster-mohitgoyal
data:
  DB_Password: UXdlcnR5QDEyMw==
  User_ID: Z295YWxtb2hpdDQ4
type: Opaque
---
apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: "kubernetes-cluster-mohitgoyal"
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: mohit-assignment
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: myapp
          image: goyalmohit48/i-mohitgoyal-master:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: special-config
          - secretRef:
              name: top-secret
  replicas: 4
  selector:
    matchLabels:
      type: front-end
      app: myapp
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "myapp-deployment-service"
  namespace: "kubernetes-cluster-mohitgoyal"
  labels:
    app: "myapp"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "myapp"
    type: "front-end"
  type: "LoadBalancer"
  loadBalancerIP: ""
