apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: mohit-assignment
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: myapp
          image: goyalmohit48/assignment:X97UFcUGtHjt13tbQKHlnsm_9BMVdyizuR3yM6VFRvoeFAviexIo_3KZlz78K0PXszLQG9uNWCdmx3kXQmOtXjZ
          imagePullPolicy: Always
          # envFrom:
          # - configMapRef:
              # name: special-config
          # - secretRef:
              # name: top-secret
  replicas: 2
  selector:
    matchLabels:
      type: front-end
      app: myapp