apiVersion: apps/v1
kind: Namespace
metadata:
  name: kubernetes-cluster-mohitgoyal 
  labels:
    name: kubernetes-cluster-mohitgoyal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  template:
    metadata:
      name: mohit-assignment
      namespace: "kubernetes-cluster-mohitgoyal"
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: myapp
          image: goyalmohit48/i-mohitgoyal-master:latest
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: special-config
          - secretRef:
              name: top-secret
  replicas: 4
  selector:
    matchLabels:
      type: front-end
      app: myapp
---
apiVersion: apps/v1
kind: "Service"
metadata:
  name: "myapp-deployment-service"
  namespace: "kubernetes-cluster-mohitgoyal"
  labels:
    app: "myapp"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "myapp"
    type: "front-end"
  type: "LoadBalancer"
  loadBalancerIP: ""
